#!/usr/bin/env bash
#
# build-aureon.sh — Build a custom Debian (bookworm) live ISO with GNOME
# desktop and user-defined package extensions via live-build (lb)
#
# Usage:
#   sudo ./build-aureon.sh
#
# Requires: live-build (lb), sudo privileges, internet access to mirrors
#
set -euo pipefail
IFS=$'\n\t'

# ------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------
DISTRIBUTION="${DISTRIBUTION:-bookworm}"
ARCHITECTURE="${ARCHITECTURE:-amd64}"
BUILD_DIR="${BUILD_DIR:-$(pwd)}"
OUTPUT_DIR="${OUTPUT_DIR:-$(pwd)/output}"
LOG_FILE="${LOG_FILE:-$BUILD_DIR/build-$(date +%Y%m%d-%H%M%S).log}"

EXTENSIONS_FILE="${EXTENSIONS_FILE:-$BUILD_DIR/my_extensions.txt}"
PACKAGE_LIST_DIR="$BUILD_DIR/config/package-lists"
PACKAGE_LIST_FILE="$PACKAGE_LIST_DIR/aureon.list.chroot"

MIRROR_BOOTSTRAP="https://deb.debian.org/debian"
MIRROR_CHROOT="https://deb.debian.org/debian"
MIRROR_CHROOT_SECURITY="https://security.debian.org/debian-security"
MIRROR_BINARY="https://deb.debian.org/debian"
MIRROR_BINARY_SECURITY="https://security.debian.org/debian-security"

# Base desktop packages that must always be present, regardless of
# what's in my_extensions.txt
BASE_DESKTOP_PACKAGES=(
    task-gnome-desktop
    xorg
    gdm3
)

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
log()  { printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" | tee -a "$LOG_FILE"; }
info() { log "[+] $*"; }
ok()   { log "[✓] $*"; }
err()  { log "[✗] $*" >&2; }

cleanup_on_error() {
    local exit_code=$?
    if [ $exit_code -ne 0 ]; then
        err "Build failed with exit code $exit_code. See $LOG_FILE for details."
    fi
    exit $exit_code
}
trap cleanup_on_error EXIT

require_root() {
    if [ "$(id -u)" -ne 0 ]; then
        err "This script must be run as root (use sudo)."
        exit 1
    fi
}

require_cmd() {
    if ! command -v "$1" >/dev/null 2>&1; then
        err "Required command '$1' not found. Install it (e.g. 'apt install live-build') and retry."
        exit 1
    fi
}

# ------------------------------------------------------------------
# Pre-flight checks
# ------------------------------------------------------------------
preflight() {
    info "Running pre-flight checks..."
    require_root
    require_cmd lb
    require_cmd mksquashfs

    if [ ! -f "$EXTENSIONS_FILE" ]; then
        err "Extensions file not found: $EXTENSIONS_FILE"
        err "Create it first, e.g.:"
        err "  echo 'gnome-shell-extension-dash-to-dock' > $EXTENSIONS_FILE"
        exit 1
    fi

    mkdir -p "$OUTPUT_DIR"
    touch "$LOG_FILE"
    ok "Pre-flight checks passed."
}

# ------------------------------------------------------------------
# Clean previous build artifacts
# SAFETY: config/ is intentionally NEVER deleted here, so your
# package lists, hooks, and includes persist across rebuilds.
# ------------------------------------------------------------------
clean_previous() {
    info "Cleaning previous build artifacts (config/ preserved)..."
    lb clean --purge >>"$LOG_FILE" 2>&1 || true
    # Deliberately NOT removing config/ — see script header safety note.
    ok "Clean complete. config/ left untouched."
}

# ------------------------------------------------------------------
# Configure the live-build environment
# ------------------------------------------------------------------
configure_build() {
    info "Configuring live-build (distribution=$DISTRIBUTION, arch=$ARCHITECTURE)..."
    lb config \
        --distribution "$DISTRIBUTION" \
        --architectures "$ARCHITECTURE" \
        --archive-areas "main contrib non-free non-free-firmware" \
        --mirror-bootstrap "$MIRROR_BOOTSTRAP" \
        --mirror-chroot "$MIRROR_CHROOT" \
        --mirror-chroot-security "$MIRROR_CHROOT_SECURITY" \
        --mirror-binary "$MIRROR_BINARY" \
        --mirror-binary-security "$MIRROR_BINARY_SECURITY" \
        >>"$LOG_FILE" 2>&1
    ok "Configuration complete."
}

# ------------------------------------------------------------------
# Build the package list from BASE_DESKTOP_PACKAGES + my_extensions.txt
#
# live-build has no `lb config --packages` flag. The supported way to
# inject packages is a file under config/package-lists/*.list.chroot,
# which live-build reads automatically during the chroot stage. This
# function generates that file from your extensions source-of-truth.
# ------------------------------------------------------------------
build_package_list() {
    info "Building package list from $EXTENSIONS_FILE..."
    mkdir -p "$PACKAGE_LIST_DIR"

    {
        echo "# Auto-generated by build-aureon.sh on $(date)"
        echo "# Do not edit directly — edit my_extensions.txt instead."
        echo ""
        echo "# --- Base desktop environment (always included) ---"
        for pkg in "${BASE_DESKTOP_PACKAGES[@]}"; do
            echo "$pkg"
        done
        echo ""
        echo "# --- Extensions from my_extensions.txt ---"
    } > "$PACKAGE_LIST_FILE"

    local count=0
    while IFS= read -r line || [ -n "$line" ]; do
        # Trim whitespace
        line="$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
        # Skip blank lines and comments
        [ -z "$line" ] && continue
        [[ "$line" == \#* ]] && continue
        echo "$line" >> "$PACKAGE_LIST_FILE"
        count=$((count + 1))
    done < "$EXTENSIONS_FILE"

    ok "Package list written to $PACKAGE_LIST_FILE ($count extension(s) added)."
}

# ------------------------------------------------------------------
# Run the actual build
# ------------------------------------------------------------------
run_build() {
    info "Starting build (this may take a while)..."
    if ! lb build 2>&1 | tee -a "$LOG_FILE"; then
        err "lb build failed."
        exit 1
    fi
    ok "Build stage complete."
}

# ------------------------------------------------------------------
# Collect the resulting ISO
# ------------------------------------------------------------------
save_iso() {
    info "Saving ISO to $OUTPUT_DIR..."
    local found=0
    while IFS= read -r -d '' iso; do
        cp -v "$iso" "$OUTPUT_DIR/" | tee -a "$LOG_FILE"
        found=1
    done < <(find "$BUILD_DIR" -maxdepth 1 -name "*.iso" -print0)

    if [ "$found" -eq 0 ]; then
        err "No ISO file found after build — something went wrong."
        exit 1
    fi
    ok "ISO saved successfully."
}

# ------------------------------------------------------------------
# Checksums for release integrity
# ------------------------------------------------------------------
generate_checksums() {
    info "Generating checksums..."
    (
        cd "$OUTPUT_DIR"
        for iso in *.iso; do
            [ -e "$iso" ] || continue
            sha256sum "$iso" > "${iso}.sha256"
            ok "Checksum written: ${iso}.sha256"
        done
    )
}

# ------------------------------------------------------------------
# Main
# ------------------------------------------------------------------
main() {
    info "=== Aureon Live ISO Build Started ==="
    preflight
    clean_previous
    configure_build
    build_package_list
    run_build
    save_iso
    generate_checksums
    ok "=== Build completed successfully. Output in: $OUTPUT_DIR ==="
}

main "$@"
