org.gnome.shell.extensions.system-monitor show-cpu true
org.gnome.shell.extensions.system-monitor show-download true
org.gnome.shell.extensions.system-monitor show-memory true
org.gnome.shell.extensions.system-monitor show-swap true
org.gnome.shell.extensions.system-monitor show-upload true
