org.gnome.shell.extensions.window-list display-all-workspaces false
org.gnome.shell.extensions.window-list embed-previews true
org.gnome.shell.extensions.window-list grouping-mode 'never'
org.gnome.shell.extensions.window-list show-on-all-monitors false
